queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=Check Dependencies
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
    #   - "#approved-reviews-by>=2"
      - check-success=build
      - label=ready-to-merge
      # - check-success=Check Dependencies
    actions:
      queue:
        name: default