queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=Check Dependencies
pull_request_rules:
  - name: automatic update for PR marked as “ready-to-merge“
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label="ready-to-merge"
    actions:
      update:
  - name: merge using the merge queue
    conditions:
      - base=main
    #   - "#approved-reviews-by>=2"
      - check-success=build
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label=ready-to-merge
      # - check-success=Check Dependencies
    actions:
      queue:
        name: default
