queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=Check Dependencies
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success=build
      - label=ready-to-merge
    actions:
      queue:
        name: default
        
#   - name: update when dependency check fails in order to retrigger check
#     conditions:
#       - base=main
#       - check-failed=Check Dependencies
#       - label=ready-to-merge
#     actions:
#       update:
