queue_rules:
  - name: default
    conditions:
      - check-success=Check Dependencies
      - check-success=build
      
pull_request_rules:
  - name: automatic merge for PR marked as "ready-to-merge"
    conditions:
      - base=main
      - check-success=build
      - label=ready-to-merge
    actions:
      queue:
        name: default
    
 - name: automatic update for PR that failed pr-dependency-check and is marked as "ready-to-merge"
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - check-failed=Check Dependencies
      - label=ready-to-merge
    actions:
      update:
