queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=Check Dependencies
pull_request_rules:
  - name: automatic merge for PR marked as "ready-to-merge"
    conditions:
      - base=main
      - check-success=build
      - label=ready-to-merge
    actions:
      queue:
        name: default
    
    - name: automatic update for PR marked as "ready-to-merge"
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
      - label=ready-to-merge
    actions:
      update:
