name: PR-Dependency

on: [pull_request, push]

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@main
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
